//! 业务服务层

pub mod user;
pub mod user_ext;
pub mod user_test;
pub mod api_key;
pub mod api_key_test;
pub mod account;
pub mod billing;
pub mod billing_test;
pub mod scheduler;
pub mod scheduler_test;
pub mod oauth;
pub mod credential;
pub mod rate_limit;
pub mod concurrency;
pub mod subscription;
pub mod subscription_test;
pub mod redemption;
pub mod redemption_test;
pub mod announcement;
pub mod announcement_test;
pub mod backup;
pub mod user_group;
pub mod email;
pub mod password_reset;
pub mod password_reset_test;
pub mod audit;
pub mod permission;
pub mod totp;
#[cfg(test)]
mod totp_test;

pub use user::{UserService, LoginResponse, TotpStatus, TotpSetupResponse};
pub use api_key::ApiKeyService;
pub use account::AccountService;
pub use billing::BillingService;
pub use scheduler::SchedulerService;
pub use oauth::OAuthService;
pub use credential::CredentialService;
pub use rate_limit::{RedisRateLimiter, DistributedRateLimiter, RateLimitConfig};
pub use concurrency::{ConcurrencyController, ConcurrencyConfig};
pub use subscription::SubscriptionService;
pub use redemption::RedemptionService;
pub use announcement::AnnouncementService;
pub use backup::BackupService;
pub use user_group::UserGroupService;
pub use email::{EmailConfig, EmailSender, SmtpEmailSender, MockEmailSender};
pub use password_reset::PasswordResetService;
pub use audit::{AuditService, AuditEntry, AuditFilter, AsyncAuditLogger};
pub use permission::{PermissionService, Role, Permission, PermissionGroup, PermissionConfig};
pub use totp::TotpService;
